logging:
  level:
    root: INFO
    org.hibernate.envers.boot: OFF
    org.hibernate.SQL: DEBUG
    com.fasterxml.jackson.databind: DEBUG
    org.apache.kafka.clients.admin: ERROR
    org.apache.kafka.clients: ERROR
    org.apache.kafka.common.metrics: ERROR
    org.apache.kafka.common.utils.AppInfoParser: ERROR
    org.apache.kafka.common.config: ERROR

spring:
  application:
    name: libra
  datasource:
    url: jdbc:postgresql://localhost:5432/libra
    username: libra
    password: libra
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      org.hibernate.envers.default_schema: history
      org.hibernate.envers.audit_table_suffix: _hist
      org.hibernate.envers.store_data_at_delete: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
app:
  cors:
    allowed-origins:
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
    allow-credentials: true